require('settings')
require('colorschemes.decay')
require('mappings')
require('lsp-config.language-servers')
require('lsp-config.cmp')
require('plugins')
require('plugins.treesitter-config')
require('plugins.lualine-config')
require('plugins.presence-config')
require('plugins.fterm-config')
require('plugins.nvim-tree-config')
require('plugins.bufferline-config')
require('plugins.glow-config')
require('plugins.dashboard-config')
require('plugins.telescope-config')
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#b6becb", bg = "#1a1e24" })
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#b6beca", bg = "#1a1e23" })
